import { AuthClient } from '@dfinity/auth-client';
import { Actor, HttpAgent } from '@dfinity/agent';
import { Principal } from '@dfinity/principal';

// Import canister declarations (these will be generated by dfx)
import { idlFactory as identityIdl } from '../declarations/identity';
import { idlFactory as professionalIdl } from '../declarations/professional';
import { idlFactory as verificationIdl } from '../declarations/verification';
import { idlFactory as storageIdl } from '../declarations/storage';
import { idlFactory as adminIdl } from '../declarations/admin';

class AuthService {
  constructor() {
    this.authClient = null;
    this.identity = null;
    this.principal = null;
    this.actors = {};
    this.isAuthenticated = false;
  }

  async init() {
    try {
      this.authClient = await AuthClient.create();
      
      if (await this.authClient.isAuthenticated()) {
        this.identity = this.authClient.getIdentity();
        this.principal = this.identity.getPrincipal();
        this.isAuthenticated = true;
        await this.initializeActors();
      }
      
      return this.isAuthenticated;
    } catch (error) {
      console.error('Failed to initialize auth service:', error);
      return false;
    }
  }

  async login() {
    try {
      return new Promise((resolve, reject) => {
        this.authClient.login({
          identityProvider: process.env.REACT_APP_INTERNET_IDENTITY_URL || 
                           (process.env.NODE_ENV === 'development' 
                             ? `http://localhost:4943?canister=${process.env.REACT_APP_INTERNET_IDENTITY_CANISTER_ID}`
                             : 'https://identity.ic0.app'),
          onSuccess: async () => {
            this.identity = this.authClient.getIdentity();
            this.principal = this.identity.getPrincipal();
            this.isAuthenticated = true;
            
            await this.initializeActors();
            resolve(true);
          },
          onError: (error) => {
            console.error('Login failed:', error);
            reject(error);
          },
          // Optional: customize the login window
          windowOpenerFeatures: 'toolbar=0,location=0,menubar=0,width=500,height=500,left=100,top=100',
        });
      });
    } catch (error) {
      console.error('Login error:', error);
      throw error;
    }
  }

  async logout() {
    try {
      await this.authClient.logout();
      this.identity = null;
      this.principal = null;
      this.isAuthenticated = false;
      this.actors = {};
    } catch (error) {
      console.error('Logout error:', error);
      throw error;
    }
  }

  async initializeActors() {
    if (!this.identity) {
      throw new Error('No identity available');
    }

    const agent = new HttpAgent({
      identity: this.identity,
      host: process.env.REACT_APP_IC_HOST || 
            (process.env.NODE_ENV === 'development' ? 'http://localhost:4943' : 'https://ic0.app'),
    });

    // In development, fetch root key for local replica
    if (process.env.NODE_ENV === 'development') {
      try {
        await agent.fetchRootKey();
      } catch (error) {
        console.warn('Failed to fetch root key:', error);
      }
    }

    // Initialize all canister actors
    this.actors = {
      identity: Actor.createActor(identityIdl, {
        agent,
        canisterId: process.env.REACT_APP_IDENTITY_CANISTER_ID,
      }),
      professional: Actor.createActor(professionalIdl, {
        agent,
        canisterId: process.env.REACT_APP_PROFESSIONAL_CANISTER_ID,
      }),
      verification: Actor.createActor(verificationIdl, {
        agent,
        canisterId: process.env.REACT_APP_VERIFICATION_CANISTER_ID,
      }),
      storage: Actor.createActor(storageIdl, {
        agent,
        canisterId: process.env.REACT_APP_STORAGE_CANISTER_ID,
      }),
      admin: Actor.createActor(adminIdl, {
        agent,
        canisterId: process.env.REACT_APP_ADMIN_CANISTER_ID,
      }),
    };
  }

  getActor(canisterName) {
    if (!this.isAuthenticated) {
      throw new Error('User not authenticated');
    }
    
    const actor = this.actors[canisterName];
    if (!actor) {
      throw new Error(`Actor for ${canisterName} not found`);
    }
    
    return actor;
  }

  getPrincipal() {
    return this.principal;
  }

  getPrincipalText() {
    return this.principal ? this.principal.toText() : null;
  }

  isLoggedIn() {
    return this.isAuthenticated;
  }

  // Helper method to handle canister calls with error handling
  async callCanister(canisterName, methodName, args = []) {
    try {
      const actor = this.getActor(canisterName);
      const result = await actor[methodName](...args);
      
      // Handle Result types from Rust canisters
      if (result && typeof result === 'object' && ('Ok' in result || 'Err' in result)) {
        if ('Ok' in result) {
          return result.Ok;
        } else {
          throw new Error(`Canister error: ${JSON.stringify(result.Err)}`);
        }
      }
      
      return result;
    } catch (error) {
      console.error(`Error calling ${canisterName}.${methodName}:`, error);
      throw error;
    }
  }

  // Identity canister methods
  async createIdentity(biometricHash, professionalDataHash, metadata) {
    return this.callCanister('identity', 'create_user_identity', [
      biometricHash,
      professionalDataHash,
      metadata ? [metadata] : []
    ]);
  }

  async getIdentity(principal) {
    return this.callCanister('identity', 'get_user_identity', [principal || this.principal]);
  }

  async verifyBiometric(principal, biometricHash) {
    return this.callCanister('identity', 'verify_biometric_hash', [
      principal || this.principal,
      biometricHash
    ]);
  }

  async getUserRole(principal) {
    return this.callCanister('identity', 'get_role', [principal || this.principal]);
  }

  // Professional canister methods
  async addProfessionalRecord(record) {
    return this.callCanister('professional', 'add_professional_record', [record]);
  }

  async getProfessionalProfile(principal) {
    return this.callCanister('professional', 'get_professional_profile', [principal || this.principal]);
  }

  async addSkillEndorsement(userPrincipal, skill, title, organization, strength, notes) {
    return this.callCanister('professional', 'add_skill_endorsement', [
      userPrincipal,
      skill,
      title,
      organization,
      strength,
      notes ? [notes] : []
    ]);
  }

  // Verification canister methods
  async createVerification(request) {
    return this.callCanister('verification', 'create_verification', [request]);
  }

  async getUserVerifications(principal) {
    return this.callCanister('verification', 'get_user_verification_requests', [principal || this.principal]);
  }

  // Storage canister methods
  async uploadDocument(request) {
    return this.callCanister('storage', 'upload_document', [request]);
  }

  async downloadDocument(documentId) {
    return this.callCanister('storage', 'download_document', [documentId]);
  }

  async getUserDocuments(principal) {
    return this.callCanister('storage', 'get_user_document_list', [principal || this.principal]);
  }

  async shareDocument(request) {
    return this.callCanister('storage', 'share_document', [request]);
  }

  // Admin canister methods (admin only)
  async getSystemStats() {
    return this.callCanister('admin', 'get_system_statistics', []);
  }

  async getAuditLog(limit) {
    return this.callCanister('admin', 'get_audit_log', [limit ? [limit] : []]);
  }

  async performHealthCheck() {
    return this.callCanister('admin', 'perform_health_check', []);
  }
}

// Create singleton instance
const authService = new AuthService();

export default authService;
